# Generate Correct Answers .csv up to 4th decimal place

In [6]:
import pandas as pd

import time
import os

# Função para ler o arquivo CSV de maneira otimizada
def read_large_csv(file_path):
    # Usando o parâmetro 'usecols' para carregar apenas as colunas necessárias
    cols_needed = ['NU_DOCUMENTO', 'VALOR_NOMINAL', 'VALOR_PRESENTE', 'VALOR_AQUISICAO']
    df = pd.read_csv(file_path, usecols=cols_needed, sep=";", thousands=",", on_bad_lines='warn')
    df["VALOR_NOMINAL"] = pd.to_numeric(df["VALOR_NOMINAL"])
    df["VALOR_PRESENTE"] = pd.to_numeric(df["VALOR_PRESENTE"])
    df["VALOR_AQUISICAO"] = pd.to_numeric(df["VALOR_AQUISICAO"])
    print(df.head())
    return df

# Função para calcular estatísticas
def calculate_statistics(df, entity_filter=None):
    # Calculando as estatísticas
    stats = df.groupby('NU_DOCUMENTO').agg(
        VALOR_NOMINAL_SUM=('VALOR_NOMINAL', 'sum'),
        VALOR_NOMINAL_AVG=('VALOR_NOMINAL', 'mean'),
        VALOR_NOMINAL_MAX=('VALOR_NOMINAL', 'max'),
        VALOR_NOMINAL_MIN=('VALOR_NOMINAL', 'min'),
        
        VALOR_PRESENTE_SUM=('VALOR_PRESENTE', 'sum'),
        VALOR_PRESENTE_AVG=('VALOR_PRESENTE', 'mean'),
        VALOR_PRESENTE_MAX=('VALOR_PRESENTE', 'max'),
        VALOR_PRESENTE_MIN=('VALOR_PRESENTE', 'min'),
        
        VALOR_AQUISICAO_SUM=('VALOR_AQUISICAO', 'sum'),
        VALOR_AQUISICAO_AVG=('VALOR_AQUISICAO', 'mean'),
        VALOR_AQUISICAO_MAX=('VALOR_AQUISICAO', 'max'),
        VALOR_AQUISICAO_MIN=('VALOR_AQUISICAO', 'min')
    ).reset_index()

    return stats

# Função para salvar as estatísticas em um arquivo CSV
def save_statistics_to_csv(stats_df, output_file):
    stats_df.to_csv(output_file, index=False)
    print(f"Estatísticas salvas em {output_file}")

# Função principal para executar o desafio
def main(input_path, entity_filter=None, output_file="estatisticas_financeiras.csv"):
    output_dir = os.getcwd() + "/output/"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    # Leitura dos dados do arquivo CSV
    start_time = time.time()
    df_lst = []
    for file in os.listdir(input_path):
        if (".csv" in file) and not ("Zone.Identifier" in file):
            file_path = input_path + file
            print(file_path)
            df_lst.append(read_large_csv(file_path))

    df = pd.concat(df_lst)
    print(f"Tempo de leitura dos arquivos: {time.time() - start_time:.2f} segundos")

    # Cálculo das estatísticas
    start_time = time.time()
    stats = calculate_statistics(df, entity_filter)
    print(f"Tempo de cálculo das estatísticas: {time.time() - start_time:.2f} segundos")

    # Salvando as estatísticas em um novo arquivo CSV
    output_file_path = output_dir + output_file
    save_statistics_to_csv(stats, output_file_path)

input_file = os.getcwd() + "/files/"  # Substitua pelo caminho do seu arquivo
main(input_file)

/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0047.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0           9.02            2.92             2.89     116679461
1          77.23           46.05            45.65     116678411
2          38.61           18.54            18.38     116678411
3          19.31            7.47             7.41     116678411
4          13.38            4.18             4.14     116678411
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0044.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0          95.67           74.69            73.92     111433146
1          66.97           42.14            41.70     111433146
2          62.50           31.67            31.34     111433146
3          46.88           19.14            18.94     111433146
4          23.44            7.71             7.63     111433146
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0040.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0          30.17            9.93             9.83     109327240
1          28.16            7.47             7.39     109327240
2          48.70           48.00            47.48     108425838
3          58.44           46.39            45.91     108425838
4          40.91           26.17            25.90     108425838
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0042.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0          25.52           10.05             9.95     115122649
1          12.75            4.04             4.00     115122649
2           6.38            1.63             1.61     115122649
3           6.78            0.91             0.90     115122649
4          13.98            6.48             6.41     107816680
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0039.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0           7.36            3.34             3.31     113601173
1          37.45           31.97            31.64     109675677
2          34.96           24.05            23.80     109675677
3          21.75           12.05            11.93     109675677
4          16.88            4.48             4.43     109666602
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0045.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0         306.16          239.04           236.57     107812955
1           8.81            2.90             2.87     109218899
2           5.01            1.32             1.31     109218899
3           5.80            1.24             1.23     109218899
4          35.06           29.38            29.08     114775107
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0043.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0           8.86            1.45             1.45     117100090
1         120.73          119.13           119.03     117100968
2           6.97            0.98             0.98     117100968
3          20.37            8.79             8.78     117329512
4          10.19            3.54             3.54     117329512
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0046.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0          12.20            6.65             6.59     116870271
1           6.10            2.67             2.65     116870271
2          68.44           65.34            64.79     116629004
3          63.88           49.72            49.32     116629004
4          46.61           29.59            29.35     116629004
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_001.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0         169.67          101.16            99.94     106096977
1          84.84           40.74            40.25     106096977
2          55.68           52.08            51.44     106135870
3           5.63            1.79             1.77     106135984
4         160.27          147.19           145.37     106136007
/home/clib/Workspace/go-performance-challenge-kanastra/files/58148845000109_Estoque_PICPAY FGTS FIDC_0041.csv
   VALOR_NOMINAL  VALOR_PRESENTE  VALOR_AQUISICAO  NU_DOCUMENTO
0          26.41           15.18            15.02     110918745
1          19.80            9.16             9.07     110918745
2          17.35            6.48             6.41     110918745
3           8.68            2.61             2.58     110918745
4           5.23            0.82             0.81     110918745
Tempo de leitura dos arquivos: 5.71 segundos
Tempo de cálculo das estatísticas: 1.08 segundos
Estatísticas salvas em /home/clib/Workspace/go-performance-challenge-kanastra/output/estatisticas_financeiras.csv

# Check is answers match the GO generated calculations

In [62]:
import pandas as pd

cols_names = ['NU_DOCUMENTO', 'VALOR_NOMINAL_SUM','VALOR_NOMINAL_AVG','VALOR_NOMINAL_MAX',
                 'VALOR_NOMINAL_MIN','VALOR_PRESENTE_SUM','VALOR_PRESENTE_AVG',
                 'VALOR_PRESENTE_MAX','VALOR_PRESENTE_MIN','VALOR_AQUISICAO_SUM',
                 'VALOR_AQUISICAO_AVG' ,'VALOR_AQUISICAO_MAX','VALOR_AQUISICAO_MIN']

cols_types = {'NU_DOCUMENTO':int, 'VALOR_NOMINAL_SUM':float,'VALOR_NOMINAL_AVG':float,'VALOR_NOMINAL_MAX':float,
                 'VALOR_NOMINAL_MIN':float,'VALOR_PRESENTE_SUM':float,'VALOR_PRESENTE_AVG':float,
                 'VALOR_PRESENTE_MAX':float,'VALOR_PRESENTE_MIN':float,'VALOR_AQUISICAO_SUM':float,
                 'VALOR_AQUISICAO_AVG':float ,'VALOR_AQUISICAO_MAX':float,'VALOR_AQUISICAO_MIN':float}

calculations_file = 'output/calculations.csv'
df_calculations = pd.read_csv(calculations_file, names=cols_names, dtype=cols_types, decimal='.', skiprows=1)
df_calculations = df_calculations.sort_values(by=['NU_DOCUMENTO']).reset_index(drop=True)

answers_file = 'output/estatisticas_financeiras.csv'
df_answers = pd.read_csv(answers_file, names=cols_names, dtype=cols_types, decimal='.', skiprows=1)
df_answers = df_answers.sort_values(by=['NU_DOCUMENTO']).reset_index(drop=True)

In [63]:
df_calculations.info()
df_calculations

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009934 entries, 0 to 1009933
Data columns (total 13 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   NU_DOCUMENTO         1009934 non-null  int64
 1   VALOR_NOMINAL_SUM    1009934 non-null  float64
 2   VALOR_NOMINAL_AVG    1009934 non-null  float64
 3   VALOR_NOMINAL_MAX    1009934 non-null  float64
 4   VALOR_NOMINAL_MIN    1009934 non-null  float64
 5   VALOR_PRESENTE_SUM   1009934 non-null  float64
 6   VALOR_PRESENTE_AVG   1009934 non-null  float64
 7   VALOR_PRESENTE_MAX   1009934 non-null  float64
 8   VALOR_PRESENTE_MIN   1009934 non-null  float64
 9   VALOR_AQUISICAO_SUM  1009934 non-null  float64
 10  VALOR_AQUISICAO_AVG  1009934 non-null  float64
 11  VALOR_AQUISICAO_MAX  1009934 non-null  float64
 12  VALOR_AQUISICAO_MIN  1009934 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 100.2 MB

,NU_DOCUMENTO,VALOR_NOMINAL_SUM,VALOR_NOMINAL_AVG,VALOR_NOMINAL_MAX,VALOR_NOMINAL_MIN,VALOR_PRESENTE_SUM,VALOR_PRESENTE_AVG,VALOR_PRESENTE_MAX,VALOR_PRESENTE_MIN,VALOR_AQUISICAO_SUM,VALOR_AQUISICAO_AVG,VALOR_AQUISICAO_MAX,VALOR_AQUISICAO_MIN
0,103217752,345.230000,115.076670,128.71,102.96,202.73999,67.579994,81.04,47.68,200.31000,66.770000,80.07,47.11
1,103217757,416.779970,46.308884,111.62,8.47,239.51000,26.612220,95.34,1.29,236.64001,26.293335,94.19,1.27
2,103217898,21.820000,10.910000,14.55,7.27,7.90000,3.950000,5.63,2.27,7.80000,3.900000,5.56,2.24
3,103218380,623.120000,311.560000,338.74,284.38,267.88998,133.944990,159.79,108.10,264.66998,132.334990,157.87,106.80
4,103218381,70.100006,35.050003,40.06,30.04,41.14000,20.570000,25.64,15.50,40.64000,20.320000,25.33,15.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009929,118173190,925.800000,185.160000,433.58,33.15,323.28000,64.656000,180.16,5.81,323.28000,64.656000,180.16,5.81
1009930,118173254,322.660000,161.330000,261.79,60.87,236.90000,118.450000,215.76,21.14,236.90000,118.450000,215.76,21.14
1009931,118173259,42.690000,42.690000,42.69,42.69,26.88000,26.880000,26.88,26.88,26.88000,26.880000,26.88,26.88
1009932,118173310,85.640000,42.820000,44.29,41.35,68.74000,34.370000,39.23,29.51,68.74000,34.370000,39.23,29.51
1009933,118173378,131.040000,26.207998,60.52,5.92,101.31000,20.262000,58.69,1.02,101.31000,20.262000,58.69,1.02

In [64]:
df_answers.info()
df_answers

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009934 entries, 0 to 1009933
Data columns (total 13 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   NU_DOCUMENTO         1009934 non-null  int64
 1   VALOR_NOMINAL_SUM    1009934 non-null  float64
 2   VALOR_NOMINAL_AVG    1009934 non-null  float64
 3   VALOR_NOMINAL_MAX    1009934 non-null  float64
 4   VALOR_NOMINAL_MIN    1009934 non-null  float64
 5   VALOR_PRESENTE_SUM   1009934 non-null  float64
 6   VALOR_PRESENTE_AVG   1009934 non-null  float64
 7   VALOR_PRESENTE_MAX   1009934 non-null  float64
 8   VALOR_PRESENTE_MIN   1009934 non-null  float64
 9   VALOR_AQUISICAO_SUM  1009934 non-null  float64
 10  VALOR_AQUISICAO_AVG  1009934 non-null  float64
 11  VALOR_AQUISICAO_MAX  1009934 non-null  float64
 12  VALOR_AQUISICAO_MIN  1009934 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 100.2 MB

,NU_DOCUMENTO,VALOR_NOMINAL_SUM,VALOR_NOMINAL_AVG,VALOR_NOMINAL_MAX,VALOR_NOMINAL_MIN,VALOR_PRESENTE_SUM,VALOR_PRESENTE_AVG,VALOR_PRESENTE_MAX,VALOR_PRESENTE_MIN,VALOR_AQUISICAO_SUM,VALOR_AQUISICAO_AVG,VALOR_AQUISICAO_MAX,VALOR_AQUISICAO_MIN
0,103217752,345.23,115.076667,128.71,102.96,202.74,67.580000,81.04,47.68,200.31,66.770000,80.07,47.11
1,103217757,416.78,46.308889,111.62,8.47,239.51,26.612222,95.34,1.29,236.64,26.293333,94.19,1.27
2,103217898,21.82,10.910000,14.55,7.27,7.90,3.950000,5.63,2.27,7.80,3.900000,5.56,2.24
3,103218380,623.12,311.560000,338.74,284.38,267.89,133.945000,159.79,108.10,264.67,132.335000,157.87,106.80
4,103218381,70.10,35.050000,40.06,30.04,41.14,20.570000,25.64,15.50,40.64,20.320000,25.33,15.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009929,118173190,925.80,185.160000,433.58,33.15,323.28,64.656000,180.16,5.81,323.28,64.656000,180.16,5.81
1009930,118173254,322.66,161.330000,261.79,60.87,236.90,118.450000,215.76,21.14,236.90,118.450000,215.76,21.14
1009931,118173259,42.69,42.690000,42.69,42.69,26.88,26.880000,26.88,26.88,26.88,26.880000,26.88,26.88
1009932,118173310,85.64,42.820000,44.29,41.35,68.74,34.370000,39.23,29.51,68.74,34.370000,39.23,29.51
1009933,118173378,131.04,26.208000,60.52,5.92,101.31,20.262000,58.69,1.02,101.31,20.262000,58.69,1.02

In [ ]:
import numpy as np

# Diff of up to 3 in 2nd decimal place
mask = np.isclose(df_answers, df_calculations, atol=0.03)

# If all True
if np.all(mask):
    print("Gabarito Batido!")
else:
    print("Erro")
    # Calculate the absolute differences
    diff = (df_answers - df_calculations).abs()
    
    # Use the mask to show only the differences that exceed the tolerance
    diff_exceeding = diff.where(~mask)
    print(diff_exceeding)

345.23
Gabarito Batido!